// angular/src/app/components/biorhythm-histogram.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import {
  AspectKey,
  BiorhythmSeries,
  CHART_HEIGHT,
  CHART_WIDTH,
  MARGIN,
  yScale,
  xScale,
} from '../biorhythm';
import { BiorhythmSwitchBoard } from './biorhythm-switch-board';

@Component({
  selector: 'app-biorhythm-histogram',
  imports: [BiorhythmSwitchBoard],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <svg
      class="chart"
      [attr.viewBox]="viewBox"
      role="img"
      aria-label="Gráfico de biorritmo con ciclos físico, emocional, intelectual, espiritual, conciencia, intuición y estética"
    >
      @for (value of gridValues; track value) {
        <g>
          <line
            [attr.x1]="margin.left"
            [attr.x2]="chartWidth - margin.right"
            [attr.y1]="scaleY(value)"
            [attr.y2]="scaleY(value)"
            [attr.class]="value === 0 ? 'gridline gridline-zero' : 'gridline'"
          />
          <text
            [attr.x]="margin.left - 8"
            [attr.y]="scaleY(value)"
            class="axis-label"
            text-anchor="end"
            dy="0.32em"
          >
            {{ value }}
          </text>
        </g>
      }

      <line
        [attr.x1]="series().centerX"
        [attr.x2]="series().centerX"
        [attr.y1]="margin.top"
        [attr.y2]="chartHeight - margin.bottom"
        class="marker-line"
      />
      <text
        [attr.x]="series().centerX"
        [attr.y]="margin.top - 4"
        class="marker-label"
        text-anchor="middle"
      >
        {{ isToday() ? 'Hoy' : formatDate(selectedDate()) }}
      </text>

      @for (label of series().dateLabels; track label.offset) {
        <text
          [attr.x]="scaleX(label.index)"
          [attr.y]="chartHeight - margin.bottom + 18"
          class="axis-label"
          text-anchor="middle"
        >
          {{ formatDate(label.date) }}
        </text>
      }

      @for (line of series().lines; track line.aspect.key) {
        @if (visible()[line.aspect.key]) {
          <g>
            <path
              [attr.d]="line.path"
              fill="none"
              [attr.stroke]="line.aspect.color"
              stroke-width="2"
              [attr.stroke-dasharray]="line.aspect.dash"
              stroke-linejoin="round"
              stroke-linecap="round"
            />
            <circle
              [attr.cx]="line.markerX"
              [attr.cy]="line.markerY"
              r="5"
              [attr.fill]="line.aspect.color"
              stroke="#ffffff"
              stroke-width="2"
            >
              <title>{{ line.aspect.label }}: {{ rounded(line.currentValue) }}%</title>
            </circle>
          </g>
        }
      }
    </svg>

    <app-biorhythm-switch-board
      [lines]="series().lines"
      [visible]="visible()"
      (aspectToggle)="aspectToggle.emit($event)"
    />
  `,
})
export class BiorhythmHistogram {
  readonly series = input.required<BiorhythmSeries>();
  readonly isToday = input.required<boolean>();
  readonly selectedDate = input.required<Date>();
  readonly visible = input.required<Record<AspectKey, boolean>>();
  readonly aspectToggle = output<AspectKey>();

  readonly chartWidth = CHART_WIDTH;
  readonly chartHeight = CHART_HEIGHT;
  readonly margin = MARGIN;
  readonly viewBox = `0 0 ${CHART_WIDTH} ${CHART_HEIGHT}`;
  readonly gridValues = [100, 50, 0, -50, -100];
  readonly scaleX = xScale;
  readonly scaleY = yScale;

  formatDate(date: Date): string {
    return date.toLocaleDateString('es-ES', { day: '2-digit', month: 'short' });
  }

  rounded(value: number): number {
    return Math.round(value);
  }
}

// electron/src/components/BiorhythmHistogram.tsx
import type {Aspect, AspectKey} from "../setup-datasets.ts";
import {CHART_HEIGHT, CHART_WIDTH, MARGIN} from "../variables.ts";
import BiorhythmAspectsSwitchBoard from "./components/BiorhythmAspectsSwitchBoard.tsx";

export type BiorhythmLine = {
    aspect: Aspect;
    path: string;
    currentValue: number;
    status: string;
    markerX: number;
    markerY: number
};

export type BiorhythmSeries = {
        lines: BiorhythmLine[];
        xScale: (index: number) => number;
        yScale: (value: number) => number;
        dateLabels: { offset: number; i: number; date: Date }[];
        centerX: number
}

export default function BiorhythmHistogram(props: {
    series: BiorhythmSeries,
    today: boolean,
    selectedDate: Date,
    visible: Record<AspectKey, boolean>,
    onToggleAspect: (key: AspectKey) => void
}) {
    return <>
        <svg
            className="chart"
            viewBox={`0 0 ${CHART_WIDTH} ${CHART_HEIGHT}`}
            role="img"
            aria-label="Gráfico de biorritmo con ciclos físico, emocional, intelectual, espiritual, conciencia, intuición y estética"
        >
            {[100, 50, 0, -50, -100].map((value) => <g key={value}>
                <line x1={MARGIN.left} x2={CHART_WIDTH - MARGIN.right} y1={props.series.yScale(value)}
                      y2={props.series.yScale(value)} className={value === 0 ? 'gridline gridline-zero' : 'gridline'}/>
                <text x={MARGIN.left - 8} y={props.series.yScale(value)} className="axis-label"
                      textAnchor="end" dy="0.32em">{value}</text>
            </g>)}

            <line
                x1={props.series.centerX}
                x2={props.series.centerX}
                y1={MARGIN.top}
                y2={CHART_HEIGHT - MARGIN.bottom}
                className="marker-line"
            />
            <text x={props.series.centerX} y={MARGIN.top - 4} className="marker-label" textAnchor="middle">
                {props.today ? 'Hoy' : props.selectedDate.toLocaleDateString('es-ES', {
                    day: '2-digit',
                    month: 'short'
                })}
            </text>

            {props.series.dateLabels.map(({offset, i, date}) => <text key={offset} x={props.series.xScale(i)}
                                                                      y={CHART_HEIGHT - MARGIN.bottom + 18}
                                                                      className="axis-label" textAnchor="middle">
                {date.toLocaleDateString('es-ES', {day: '2-digit', month: 'short'})}
            </text>)}

            {props.series.lines
                .filter((line) => props.visible[line.aspect.key])
                .map((line) => <g key={line.aspect.key}>
                    <path d={line.path} fill="none" stroke={line.aspect.color} strokeWidth={2}
                          strokeDasharray={line.aspect.dash} strokeLinejoin="round" strokeLinecap="round"/>
                    <circle cx={line.markerX} cy={line.markerY} r={5} fill={line.aspect.color}
                            stroke="#ffffff" strokeWidth={2}>
                        <title>{line.aspect.label}: {Math.round(line.currentValue)}%</title>
                    </circle>
                </g>)}
        </svg>

        <BiorhythmAspectsSwitchBoard
            lines={props.series.lines}
            visible={props.visible}
            onToggleAspect={props.onToggleAspect}
        />
    </>
}
