// angular/src/app/components/biorhythm-header.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-biorhythm-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h1>Calculadora de biorritmo</h1>
    <p class="subtitle">
      Ingresa tu fecha de nacimiento para graficar tus ciclos físico, emocional e intelectual, junto
      con los aspectos complementarios: espiritual, conciencia, intuición y estética.
    </p>
  `,
})
export class BiorhythmHeader {}

// react/src/components/BiorhythmHeader.tsx

export function BiorhythmHeader() {
    return <>
        <h1>Calculadora de biorritmo</h1>
        <p className="subtitle">
            Ingresa tu fecha de nacimiento para graficar tus ciclos físico, emocional e intelectual, junto con los
            aspectos complementarios: espiritual, conciencia, intuición y estética.
        </p>
    </>;
}
